from __future__ import annotations
import struct
from typing import Dict, List, Set
from command import CommandIR, CommandDMAC
from vif import decode as vif_decode

# Assumes DMATag (Source Chain Tag) is included
class VIFPacket:
    @classmethod
    def from_file(cls, f):
        packet = cls()
        pos = f.tell()

        f.seek(pos + 0x0)
        packet.size = ((struct.unpack("<I", f.read(4))[0] & 0x3FF) + 1) * 0x10
        f.seek(pos + 0x0)
        packet.buf = f.read(packet.size)
        
        f.seek(pos)

        return packet

    def decode(self, pc: int) -> VIFPacketIR:
        DMA_IDS = ["refe", "cnt", "next", "ref", "refs", "call", "ret", "end"]

        ir = VIFPacketIR()

        # First 8 bytes are DMATag and ADDR
        dma_tag = CommandDMAC(pc)
        dma_tag.pc = pc
        dma_tag.size = self.size
        word = struct.unpack("<I", self.buf[0:4])[0]
        dma_tag.id = (word >> 28) & 0x7
        dma_tag.id_s = DMA_IDS[dma_tag.id]
        addr = struct.unpack("<I", self.buf[4:8])[0]
        dma_tag.addr = addr
        ir.add_command(dma_tag)

        # Now we should start running into VIFCode
        i = 8
        while i < self.size:
            size = vif_decode(ir, self.buf, i, pc+i)
            i += size
        
        return ir

class VIFPacketIR:
    class Label:
        # For autogenerated label prefix
        B = 0
        BAL = 1

        def __init__(self, pc: int):
            assert pc % 4 == 0
            self.pc = pc
            self.type = VIFPacketIR.Label.B
            self.refs: Set[int] = set()
            self.symbol: str | None = None

        def set_type(self, _type: int) -> None:
            # BAL takes precedence over B for autogenerated names
            self.type = max(self.type, _type)

        def set_symbol(self, symbol: str) -> None:
            self.symbol = symbol

        def add_ref(self, pc: int) -> None:
            self.refs.add(pc)

        def __str__(self) -> str:
            if self.symbol is not None:
                # If we've parsed a symbol from the ELF just use that instead
                return self.symbol

            match self.type:
                case VIFPacketIR.Label.B:
                    return f"LAB_{self.pc:X}"
                case VIFPacketIR.Label.BAL:
                    return f"SUB_{self.pc:X}"

            assert False
            return f"{self.pc:X}"
    
    def __init__(self):
        self.labels: Dict[int, VIFPacketIR.Label] = {}
        self.commands: List[CommandIR] = []

    def add_command(self, command: CommandIR):
        self.commands.append(command)

    def get_label(self, pc: int) -> VIFPacketIR.Label | None:
        return self.labels.get(pc, None)

    def get_or_new_label(self, pc: int) -> VIFPacketIR.Label:
        if pc in self.labels:
            return self.labels[pc]
        
        label = VIFPacketIR.Label(pc)
        self.labels[pc] = label
        return label
