from __future__ import annotations
import struct
from typing import Dict, List, Set, Tuple
from command import CommandIR, CommandDMAC
from vif import decode as vif_decode

# Assumes DMATag (Source Chain Tag) is included
class VIFPacket:
    @classmethod
    def from_file(cls, f):
        packet = cls()
        pos = f.tell()

        f.seek(pos + 0x0)
        packet.size = ((struct.unpack("<I", f.read(4))[0] & 0x3FF) + 1) * 0x10
        f.seek(pos + 0x0)
        packet.buf = f.read(packet.size)
        
        f.seek(pos)

        return packet

    def decode(self, pc: int) -> VIFPacketIR:
        DMA_IDS = ["refe", "cnt", "next", "ref", "refs", "call", "ret", "end"]

        ir = VIFPacketIR()

        # First 8 bytes are DMATag and ADDR
        dma_tag = CommandDMAC(pc)
        dma_tag.pc = pc
        dma_tag.size = self.size
        word = struct.unpack("<I", self.buf[0:4])[0]
        dma_tag.id = (word >> 28) & 0x7
        dma_tag.id_s = DMA_IDS[dma_tag.id]
        addr = struct.unpack("<I", self.buf[4:8])[0]
        dma_tag.addr = addr
        ir.add_command(dma_tag)

        # Now we should start running into VIFCode
        i = 8
        while i < self.size:
            size = vif_decode(ir, self.buf, i, pc+i)
            i += size
        
        # Finally resolve any forward references we have for labels
        ir.resolve_forward_labels()

        return ir

class VIFPacketIR:
    class Label:
        # For autogenerated label prefix
        B = 0
        BAL = 1

        def __init__(self, pc: int, forward_ref: bool = False):
            assert pc % 4 == 0
            self.forward_ref = False # For labels we can't yet resolve
            self.pc: int = pc
            self.type = VIFPacketIR.Label.B
            self.refs: Set[int] = set()
            self.symbol: str | None = None

        def set_type(self, _type: int) -> None:
            # BAL takes precedence over B for autogenerated names
            self.type = max(self.type, _type)

        def set_symbol(self, symbol: str) -> None:
            self.symbol = symbol

        def add_ref(self, pc: int) -> None:
            self.refs.add(pc)

        def __str__(self) -> str:
            if self.symbol is not None:
                # If we've parsed a symbol from the ELF just use that instead
                return self.symbol

            match self.type:
                case VIFPacketIR.Label.B:
                    return f"LAB_{self.pc:X}"
                case VIFPacketIR.Label.BAL:
                    return f"SUB_{self.pc:X}"

            assert False
            return f"{self.pc:X}"
        
    def __init__(self):
        self.labels: Dict[int, VIFPacketIR.Label] = {}
        self.forward_labels: Dict[int, VIFPacketIR.Label] = {}
        self.commands: List[CommandIR] = []
        # Pairs of (load_addr, size, pc) to properly resolve branch addresses to virtual PC addr
        self.load_addrs: List[Tuple[int, int, int]] = []

    def add_command(self, command: CommandIR):
        self.commands.append(command)

    def get_label(self, pc: int, forward_ref: bool = False) -> VIFPacketIR.Label | None:
        if forward_ref:
            return self.forward_labels.get(pc, None)
        return self.labels.get(pc, None)

    def get_or_new_label(self, pc: int, forward_ref: bool = False) -> VIFPacketIR.Label:
        if forward_ref:
            if pc in self.forward_labels:
                return self.forward_labels[pc]
        else:
            if pc in self.labels:
                return self.labels[pc]
        
        label = VIFPacketIR.Label(pc, forward_ref=forward_ref)
        if forward_ref:
            self.forward_labels[pc] = label
        else:
            self.labels[pc] = label
        return label

    def resolve_forward_labels(self):
        for actual_end_addr, label in self.forward_labels.copy().items():
            branch_pc = -1
            for load_addr, size, vaddr in self.load_addrs:
                if actual_end_addr in range(load_addr, load_addr+size):
                    branch_pc = vaddr + (actual_end_addr - load_addr)

            assert branch_pc != -1

            resolved_label = self.get_or_new_label(branch_pc)
            for ref in label.refs:
                resolved_label.add_ref(ref)

            self.forward_labels[actual_end_addr] = resolved_label
